#!/usr/bin/env python3
"""
Compare multiple models for instrument classification.
Runs the same instrument (VTI) through each model and records timing + output quality.

Usage:
    cd backend/tagger
    uv run compare_models.py              # run all models
    uv run compare_models.py --model openai/gpt-5.4-nano  # single model
"""

import os
import sys
import json
import time
import asyncio
import argparse
from datetime import datetime, timezone
from typing import Any

from dotenv import load_dotenv

load_dotenv(override=True)

from agent import classify_instrument, classification_to_db_format

# Models to compare
DEFAULT_MODELS = [
    "openai/gpt-5.4-nano",
    "openai/gpt-5-nano",
    "openai/gpt-4.1-nano",
]

# Test instrument — same for all models for fair comparison
TEST_INSTRUMENT = {
    "symbol": "VTI",
    "name": "Vanguard Total Stock Market ETF",
    "instrument_type": "etf",
}

RESULTS_FILE = os.path.join(os.path.dirname(__file__), "MODEL_COMPARISON.md")


def check_prerequisites(models: list[str]) -> dict[str, str]:
    """Check that required API keys are set for each model."""
    issues: dict[str, str] = {}
    has_openai = bool(os.getenv("OPENAI_API_KEY"))

    for m in models:
        if m.startswith("openai/") and not has_openai:
            issues[m] = "OPENAI_API_KEY not set"

    return issues


async def run_single_model(model_id: str) -> dict[str, Any]:
    """Classify one instrument with one model. Returns timing + result dict."""
    print(f"\n{'='*60}")
    print(f"Model: {model_id}")
    print(f"Instrument: {TEST_INSTRUMENT['symbol']} ({TEST_INSTRUMENT['name']})")
    print(f"{'='*60}")

    result: dict[str, Any] = {
        "model": model_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "symbol": TEST_INSTRUMENT["symbol"],
        "success": False,
        "elapsed_s": 0.0,
        "error": None,
        "classification": None,
    }

    t_start = time.monotonic()
    try:
        classification = await classify_instrument(
            symbol=TEST_INSTRUMENT["symbol"],
            name=TEST_INSTRUMENT["name"],
            instrument_type=TEST_INSTRUMENT["instrument_type"],
            model_id=model_id,
        )
        elapsed = time.monotonic() - t_start

        result["success"] = True
        result["elapsed_s"] = round(elapsed, 2)
        result["classification"] = {
            "symbol": classification.symbol,
            "name": classification.name,
            "type": classification.instrument_type,
            "current_price": classification.current_price,
            "asset_class": classification.allocation_asset_class.model_dump(),
            "regions": classification.allocation_regions.model_dump(),
            "sectors": classification.allocation_sectors.model_dump(),
        }

        # Summary stats
        asset_nonzero = sum(
            1 for v in classification.allocation_asset_class.model_dump().values()
            if v > 0
        )
        region_nonzero = sum(
            1 for v in classification.allocation_regions.model_dump().values()
            if v > 0
        )
        sector_nonzero = sum(
            1 for v in classification.allocation_sectors.model_dump().values()
            if v > 0
        )
        print(f"  OK  {elapsed:.2f}s | price=${classification.current_price:.2f} | "
              f"assets={asset_nonzero} regions={region_nonzero} sectors={sector_nonzero}")

    except Exception as e:
        elapsed = time.monotonic() - t_start
        result["elapsed_s"] = round(elapsed, 2)
        result["error"] = str(e)
        print(f"  FAIL  {elapsed:.2f}s | {e}")

    return result


def write_markdown(all_results: list[dict]) -> str:
    """Generate a markdown comparison report."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Model Comparison — InstrumentTagger",
        "",
        f"> Auto-generated by `compare_models.py` on {now}",
        "",
        "## Test Setup",
        "",
        f"- **Instrument**: {TEST_INSTRUMENT['symbol']} ({TEST_INSTRUMENT['name']})",
        f"- **Type**: {TEST_INSTRUMENT['instrument_type']}",
        "- **Method**: `classify_instrument()` via OpenAI Agents SDK + LiteLLM",
        "",
        "## Results Summary",
        "",
        "| # | Model | Status | Time (s) | Price ($) | Asset Classes | Regions | Sectors |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for i, r in enumerate(all_results, 1):
        status = "OK" if r["success"] else "FAIL"
        time_s = r["elapsed_s"]
        cls = r["classification"] or {}

        price = f"{cls.get('current_price', '—')}"
        asset_n = sum(1 for v in (cls.get("asset_class") or {}).values() if v > 0)
        region_n = sum(1 for v in (cls.get("regions") or {}).values() if v > 0)
        sector_n = sum(1 for v in (cls.get("sectors") or {}).values() if v > 0)

        lines.append(
            f"| {i} | `{r['model']}` | {status} | {time_s} | {price} | {asset_n} | {region_n} | {sector_n} |"
        )

    # Add error details if any
    failures = [r for r in all_results if not r["success"]]
    if failures:
        lines.append("")
        lines.append("## Failures")
        lines.append("")
        for r in failures:
            lines.append(f"- **`{r['model']}`**: {r['error']}")

    # Add detailed classification for each successful model
    lines.append("")
    lines.append("## Detailed Classifications")
    lines.append("")

    for r in all_results:
        lines.append(f"### {r['model']}")
        lines.append("")
        if not r["success"]:
            lines.append(f"*Failed: {r['error']}*")
            lines.append("")
            continue

        cls = r["classification"] or {}
        lines.append(f"- **Time**: {r['elapsed_s']}s")
        lines.append(f"- **Price**: ${cls.get('current_price', '—')}")
        lines.append("")

        # Asset class
        lines.append("**Asset Class:**")
        lines.append("")
        for k, v in sorted((cls.get("asset_class") or {}).items(), key=lambda x: -x[1]):
            if v > 0:
                lines.append(f"- {k}: {v}%")
        lines.append("")

        # Regions
        lines.append("**Regions:**")
        lines.append("")
        for k, v in sorted((cls.get("regions") or {}).items(), key=lambda x: -x[1]):
            if v > 0:
                lines.append(f"- {k}: {v}%")
        lines.append("")

        # Sectors
        lines.append("**Sectors:**")
        lines.append("")
        for k, v in sorted((cls.get("sectors") or {}).items(), key=lambda x: -x[1]):
            if v > 0:
                lines.append(f"- {k}: {v}%")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*To re-run: `cd backend/tagger && uv run compare_models.py`*")
    lines.append("")

    return "\n".join(lines)


async def main():
    parser = argparse.ArgumentParser(description="Compare models for instrument classification")
    parser.add_argument(
        "--model", type=str, default=None,
        help="Run a single model instead of all defaults"
    )
    parser.add_argument(
        "--output", type=str, default=RESULTS_FILE,
        help="Output markdown file path"
    )
    args = parser.parse_args()

    models = [args.model] if args.model else DEFAULT_MODELS

    # Check prerequisites
    issues = check_prerequisites(models)
    if issues:
        print("WARNING: Missing API keys:")
        for m, issue in issues.items():
            print(f"  - {m}: {issue}")
        if all(m in issues for m in models):
            print("\nCannot run any model — missing all required API keys.")
            sys.exit(1)
        # Filter out models with missing keys
        models = [m for m in models if m not in issues]
        print(f"\nProceeding with: {models}")

    print(f"Comparing {len(models)} model(s)...")
    print(f"Output: {args.output}")

    all_results = []
    for model_id in models:
        result = await run_single_model(model_id)
        all_results.append(result)
        # Small delay between models to avoid rate limits
        await asyncio.sleep(1.0)

    # Write report
    report = write_markdown(all_results)
    with open(args.output, "w") as f:
        f.write(report)

    print(f"\n{'='*60}")
    print(f"Report written to: {args.output}")
    print(f"Models tested: {len(all_results)}")
    print(f"Successful: {sum(1 for r in all_results if r['success'])}")
    print(f"Failed: {sum(1 for r in all_results if not r['success'])}")
    print(f"{'='*60}")


if __name__ == "__main__":
    asyncio.run(main())
